### ISSUE TITLE
 GPU Requirements

### ISSUE THREAD

**Issue by Luo-Z13** [ucas-vg/Sambor#1]
Hi there, I'm curious about the minimum computational resources required for this algorithm. I noticed in the paper that it utilized 16 GPUs. Can you provide information on the minimum GPU requirements for running this algorithm?

**Comment by wavinflaghxm** [comment]
If your computational resources are insufficient, the pre-training time will increase (given the volume of the O365 and GoldG datasets). If only inference is required, there are no constraints on the number of GPUs.

**Comment by Luo-Z13** [comment]
> If your computational resources are insufficient, the pre-training time will increase (given the volume of the O365 and GoldG datasets). If only inference is required, there are no constraints on the number of GPUs.

Thank you for your response! Could you please provide an estimate of the pre-training time using the O365 and GoldG datasets using 2 16GB V100 GPUs, as well as the pre-training time using a dataset with a volume of around 0.1 million?

**Comment by wavinflaghxm** [comment]
Sorry, we haven't used the 16GB V100, so we cannot provide an exact time. However, we reckon it may take several days.

**Comment by Luo-Z13** [comment]
> Sorry, we haven't used the 16GB V100, so we cannot provide an exact time. However, we reckon it may take several days.

Ok, thank you very much!
